NewsBlog/Controllers/ArticlesController.cs
using LibraryAngular.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NewsBlog.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NewsBlog.Controllers
{
    public class ArticlesController : Controller
    {
        private ApplicationDbContext db;

        public ArticlesController()
        {
           db = new ApplicationDbContext();
        }

        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewBag.User = User.Identity.Name;

            var articles = db.Articles.ToList().OrderByDescending(p => p.ID).ToPagedList(pageNumber, pageSize);
            return View("Index", articles);
        }


        public async Task<JsonResult> GetUserInfoByArticle(int id)
        {
            var user = (from a in db.Articles
                        join u in db.Users on a.UserID equals u.Id
                        select new
                        {
                            a.ID,
                            u.FirstName,
                            u.LastName
                        }).Where(x => x.ID == id).ToListAsync();

            var json = Json(await user, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetPublishedArticlesBySearch(string term)
        {
            var articles = (from article in db.Articles
                            join u in db.Users on article.UserID equals u.Id
                            where article.Name.Contains(term) ||
                            article.Description.Contains(term) ||
                            article.Content.Contains(term)
                        orderby article.ID descending
                        select article).Where(x=>x.isAprove==true).ToListAsync();
            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetCategories()
        {
            var categories = (from c in db.Categories select new
            {
                c.ID,
                c.CategoryName
            }).ToListAsync();
            return Json(await categories, JsonRequestBehavior.AllowGet); ;
        }

            public async Task<JsonResult> GetPublishedArticlesByCategory(string category)
        {
            var articles = (from a in db.Articles
                           join u in db.Users on a.UserID equals u.Id
                           where a.isAprove == true
                           orderby a.ViewCount descending
                           where a.Categories.CategoryName == category && a.isAprove==true
                           orderby a.ID 
                           descending
                           select new {
                            a.ID,
                            a.Name,
                            a.isAprove,
                            a.ViewCount,
                            a.CommentsCount,
                            a.DateCreate,
                            a.Description,
                            a.Categories.CategoryName,
                            u.FirstName,
                            u.LastName,
                            u.Id
            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }

        public async Task<JsonResult> GetPublishedAdminChoosedArticles()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isAdminChoose == true && a.isAprove == true
                            orderby a.ID
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetPublishedArticlesByCommentsCount()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isAprove == true
                            orderby a.CommentsCount
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }


        public async Task<JsonResult> GetPopularArticlesByCategory(string category)
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.Categories.CategoryName == category && a.isAprove == true
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).Take(4).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }


        public async Task<JsonResult> GetPublishedHotArticles()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isHotArticle==true && a.isAprove == true
                            orderby a.ID
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }

      
        public async Task<JsonResult> GetTop3PerWeekArticles()
        {
 
            var now = DateTime.Now;

            int days = now.DayOfWeek - DayOfWeek.Sunday;
            DateTime weekStart = now.AddDays(-days);
            DateTime weekEnd = weekStart.AddDays(7);

            var articles = (from a in db.Articles
                                where a.DateCreate <= weekEnd && a.DateCreate >= weekStart
                                orderby a.ViewCount descending
                                select new { a.ID, a.Name, a.ViewCount, a.CommentsCount, a.isAprove }).Where(x => x.isAprove == true).Take(3).ToListAsync();
                var json = Json(await articles, JsonRequestBehavior.AllowGet);
                json.MaxJsonLength = int.MaxValue;
                return json;

        }

        public async Task<JsonResult> GetPublishedArticles()
        {
            var articles = (from a in db.Articles join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.DateCreate descending

NewsBlog/Controllers/CommentsController.cs
using Microsoft.AspNet.Identity;
using NewsBlog.Models;
using System;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NewsBlog.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public async Task<ActionResult> Index()
        {
            return View(await db.Comments.ToListAsync());
        }

        public FileResult GetArticleImage(int id)
        {
            var cover = db.Articles.FirstOrDefault(p => p.ID == id);
            if (cover.CoverType != null)
            {
                return File(cover.CoverPath, cover.CoverType);
            }
            else
            {
                return null;
            }
        }

        public async Task<JsonResult> GetRecentComments()
        {
            var comments = (from c in db.Comments join u in db.Users on c.UserId equals u.Id join a in db.Articles on c.ArticleId equals a.ID orderby c.CommentTime descending select new {
                c.CommentBody,
                c.CommentTime,
                a.ID,
                a.Name,
                u.FirstName,
                u.LastName
            }).Take(5).ToListAsync();
            var comm =  Json(await comments, JsonRequestBehavior.AllowGet);
            comm.MaxJsonLength = int.MaxValue;
            return comm;
        }

        [AllowAnonymous]
        [OutputCache(Location = System.Web.UI.OutputCacheLocation.Any, Duration = 60)]
        public FileContentResult GetUserImage(string id)
        {
            var cover = db.Users.FirstOrDefault(p => p.Id == id);
            if (cover.Cover != null && cover.CoverType != null)
            {
                return File(cover.Cover, cover.CoverType);
            }
            else
            {
                string imageFile = System.Web.HttpContext.Current.Server.MapPath("~/Content/user.png");
                var srcImage = Image.FromFile(imageFile);
                var stream = new MemoryStream();
                srcImage.Save(stream, ImageFormat.Png);
                return File(stream.ToArray(), "image/png");
            }
        }



        [HttpGet]
        public async Task<JsonResult> CommentWall(int id)
        {
            var comments = (from c in db.Comments join u in db.Users on c.UserId equals u.Id
                            where c.ArticleId == id orderby c.CommentTime descending
                            select new
                            {   
                                c.CommentId,
                                u.FirstName,
                                u.LastName,
                                c.CommentBody,
                                u.Cover,
                                u.Id,
                                c.CommentTime,
                                c.ParentId,
                            }).ToListAsync();
            var comm = Json(await comments, JsonRequestBehavior.AllowGet);
            comm.MaxJsonLength = int.MaxValue;
            return comm;
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddComment(Comments comment)
        {
            if (ModelState.IsValid)
            {
                Article article = db.Articles.Find(comment.ArticleId);
                article.CommentsCount += 1;
                comment.CommentTime = DateTime.Now;
                db.Entry(article).State = EntityState.Modified;
                comment.UserId = User.Identity.GetUserId();
                db.Comments.Add(comment);
                db.SaveChanges();
            }
            return Json(new { });
        }


        // GET: Comments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CommentBody,CommentTime,ArticleId,UserId")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comments);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(comments);
        }

        // GET: Comments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CommentBody,CommentTime,ArticleId,UserId")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comments).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(comments);
        }

        // GET: Comments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Comments comments = await db.Comments.FindAsync(id);
            db.Comments.Remove(comments);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsBlog/Views/Home/Index.cshtml

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
   
    var options = new AjaxOptions()
    {
        UpdateTargetId = "tabledata",
        Url = Url.Action("AjaxMostPopular"),
        LoadingElementId = "loadingIndicator",
    };
}

<link href="~/Content/index.css" rel="stylesheet" />
<link href="~/Content/responsive.css" rel="stylesheet" />

<div class="row">
    <div ng-app="homeApp" ng-cloak>
        <div ng-controller="homeCtrl as vm">
            <div class="row">
                <div class="col-md-8 col-sm-8 hidden-xs">
                    <nav style="float:left">
                        <ul>
                            <li>
                                <a href="#" ng-click="getAllArticles()"><span class="glyphicon glyphicon-leaf" style="color:#4db7ad;"></span> Всі новини</a>
                            </li>

                            <li>
                                <a href="#" ng-click="getHotArticles()"><span class="glyphicon glyphicon-fire" style="color:orangered"></span> Гарячі новини</a>
                            </li>

                            <li>
                                <a href="#" ng-click="getAdminChoosedArticles()"><span class="glyphicon glyphicon-bell" style="color:#ffd800"></span>Вибір редакції </a>
                            </li>

                            <li>
                                <a href="#" ng-click="getPublishedArticlesByCommentsCount()"><span class="glyphicon glyphicon-send" style="color:dodgerblue"></span> Обговорювані</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-10 col-xs-offset-1" align="center">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input class="search" type="search" placeholder="Пошук" style="border:none;margin-left:5px; margin-right:5px; background-color:#fffad1;padding:5px;border-radius:3px;" ng-model="search">
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-xs" type="button">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>

                                        </div>

               

            </div>
            <br /><br />

            <p ng-bind="messageString" ng-show="messageString" id="alert_message" style="margin-bottom:50px;margin-left:120px;background-color:#F8FAFA; color:gray" class="animate-show animage-hide"></p>



            <div class="popular_by_week">
                <p style="color:#4db7ad">
                    Популярні за тиждень
                </p>
                <table class="table" style="table-layout:fixed">
                    <tr ng-repeat="ta in ::vm.topArticles track by $index">
                        @{
                            var uri = Url.Action("GetCoverImage", "Articles", new { id = "{{id=ta.ID}}" });
                            uri = HttpUtility.UrlDecode(uri);
                        }
                        <td>
                            <center><text style="font-size:12px; font-weight:700;"><a ng-href="@Url.Action("news", "Home")?id={{::ta.ID}}"> {{::ta.Name}} </a></text><br /></center>
                            <br />
                            <center><a ng-href="@Url.Action("news", "Home")?id={{::ta.ID}}"><img width="80%" ng-src="@uri" class="img-rounded" /></a></center>
                            <center>
                                <span class="glyphicon glyphicon-eye-open" style="color:#4db7ad; font-size:12px;"></span>
                                <text style="color:gray;font-size:12px;" ng-bind="::ta.ViewCount"></text>&nbsp;&nbsp;
                                <span class="glyphicon glyphicon-comment" style="color:#ffd800;font-size:12px;"></span>
                                <text style="color:gray;font-size:12px;" ng-bind="::ta.CommentsCount"></text>
                            </center>
                        </td>
                    </tr>
                </table>

                <p style="color:#4db7ad">
                    Категорії
                </p><br />

                <div ng-repeat="c in ::categories track by $index">
                    <a href='#' ng-click="searchCategory(c.CategoryName)" style="color:gray ; font-weight:bold; float:left; padding-left:10px;"><text style="color:yellow">&#9632;</text> {{c.CategoryName}} </a><br />
                </div>
                <br />
                <p style="color:#4db7ad">
                    Останні коментарі
                </p>
                <div class="recentComments">

                    <div ng-repeat="rc in rcomm">
                        @{
                            var url = Url.Action("GetArticleImage", "Comments", new { id = "{{id=rc.ID}}" });
                            url = HttpUtility.UrlDecode(url);
                        }
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-4">
                                    <a ng-href="@Url.Action("news", "Home")?id={{::rc.ID}}"><img ng-src="@url" style="width:100px;" class="img-rounded" /></a>
                                </div>
                                <div class="col-md-8">
                                    <text class="comment_time">{{rc.FirstName }}{{rc.LastName}}</text>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-10 col-md-offset-1 comment_body">
                                    <text class="comment_body" ng-bind-html="rc.CommentBody | unsafe"></text>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content" style="width:100%; margin:0px 5px 0px 0px;min-height:450px;">
                <br />
                <table cellspacing="0" class="table" cellpadding="0" id="MainTable">
                    <tr ng-repeat="pa in vm.items | filter:search">
                        <td>
                            <ul>
                                <li>
                                    <div class="ratio img-responsive img-circle" style="margin: 10px auto;width:100px;height:100px;background-image: url(@Url.Action("GetUserImage","Home")?id={{::pa.Id}});background-size: cover;"></div>
                                    <text ng-bind="::pa.LastName"></text>&nbsp; <text ng-bind="::pa.FirstName"></text> <br />
                                    @*<img class="rounded-circle" style="width:100px;height:100px;" ng-src="@Url.Action("GetUserImage","Home")?id={{::pa.Id}}" />*@
                                </li>
                                <li style="text-align:center;margin-left:0px;color:#4db7ad; font-size:14px;"><text ng-bind="::pa.CategoryName"></text></li>
                                  
                               
                            </ul>
                        </td>

                        <td>
                            <text style="float:left; font-size:16px; font-weight:bold; text-transform:uppercase"><a ng-href="@Url.Action("news", "Home")?id={{::pa.ID}}" style="color:gray"> {{::pa.Name}} </a></text><br />
                            <center><a ng-href="@Url.Action("news", "Home")?id={{::pa.ID}}"> <img id="cover" width="100%" ng-src="@Url.Action("GetCoverImage", "Articles")?id={{::pa.ID}}" class="img-rounded" /></a></center>
                            <span class="glyphicon glyphicon-eye-open" style="color:#4db7ad;padding-top:10px;"></span>
                            <text style="color:gray" ng-bind="::pa.ViewCount"></text>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment" style="color:#ffd800"></span>
                            <text style="color:gray" ng-bind="::pa.CommentsCount"></text>
                            <text ng-show="pa.isAdminChoose==1" style="background-color:gold; padding:3px;color:white; border-radius:2px;">Вибір редакції
                            </text>
                            &emsp;
                            <text ng-show="pa.isHotArticle==1" style="background-color:orangered; padding:3px;color:white; border-radius:2px;">
                                Гаряча новина
                            </text>

                              <div style="float:right;padding-top:10px;">
                                <span class="glyphicon glyphicon-time" aria-hidden="true" style="color:#4db7ad"></span>
                                <text style="font-size:12px;color:gray" ng-bind="::pa.DateCreate.slice(6,19) | date"> &nbsp;&nbsp;&nbsp;</text>
                            </div>
                            <br />
                            <br />
                            <text style="word-break:break-all; font-size:15px;" ng-bind="::pa.Description"></text> <br />
                            <a ng-href="@Url.Action("news", "Home")?id={{::pa.ID}}"><text id="itemName" style="float:right; font-weight:bold; color:#4db7ad">Читати далі <span style="color:#ffd800">&#9658;</span></text></a>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="row">
                <div class="col-md-12 col-xs-12 col-sm-12" align="center">
                    <!-- pager -->
                    <ul ng-if="vm.pager.pages.length" class="pagination">
                        <li ng-class="{disabled:vm.pager.currentPage === 1}">
                            <a ng-href="#" ng-click="vm.setPage(1)">Перша</a>
                        </li>
                        <li ng-class="{disabled:vm.pager.currentPage === 1}">
                            <a ng-href="#" ng-click="vm.setPage(vm.pager.currentPage - 1)">Попередня</a>
                        </li>
                        <li ng-repeat="page in vm.pager.pages" ng-class="{active:vm.pager.currentPage === page}" class="hidden-xs">
                            <a ng-href="#" ng-click="vm.setPage(page)">{{page}}</a>
                        </li>
                        <li ng-class="{disabled:vm.pager.currentPage === vm.pager.totalPages}">
                            <a ng-href="#" ng-click="vm.setPage(vm.pager.currentPage + 1)">Наступна</a>
                        </li>
                        <li ng-class="{disabled:vm.pager.currentPage === vm.pager.totalPages}" class="hidden-xs">
                            <a ng-href="#" ng-click="vm.setPage(vm.pager.totalPages)">Остання</a>
                        </li>
                    </ul>
                </div>
            </div>
            
            <div class="row">
                <hr />
                <div class="col-md-8 col-sm-12 col-xs-12" align="center">
                    <p><span class="glyphicon glyphicon-leaf" style="color:#4db7ad;"></span> <text style="font-size:22px;color:gray">Найкращі матеріали</text></p>
                </div>
            </div>
            <div class="row">
                    <div class="col-md-8 col-sm-12 col-xs-12" align="center">
                        <div class="most_popular" style="margin-top:10px">
                            @using (Ajax.BeginForm(options))
                            {
                                <table cellpadding="5">
                                    <tbody id="tabledata">
                                        @Html.Action("AjaxMostPopular")
                                    </tbody>
                                </table>
                                <input type="submit" value="Показати ще" id="showMore" /><br />
                            }
                        </div>
                    </div>
                </div>
           

            <footer style="height: 140px">
                <div class="row">
                    <div class="col-md-3 col-lg-3 col-sm-3" align="center">
                        <p><i class="glyphicon glyphicon-leaf" style="padding-right:5px; font-size:28px; color:#4DB7AD;"></i><text style="font-weight:700; font-size:24px; color:white ">News CMS</text></p>
                        <p>Розробник Плагун Олександр</p>
                    </div>
                    <div class="col-md-3 hidden-xs col-lg-3 col-sm-3">
                        <p>
                            Контактна інформація:<br/>
                                plagun98@gmail.com
                        </p>
                    </div>
                    <div class="col-md-3 hidden-xs col-lg-3 col-sm-3">
                        <p>
                            ВНЗ:<br /> <a href="https://kpi.ua">
                                НТУУ "КПІ ім. І. Сікорського"
                            </a>.
                        </p>
                    </div>
                    <div class="col-md-3 hidden-xs col-lg-3 col-sm-3">
                        <p>
                            GitHub:<br /> <a href="https://github.com/plagun98">
    github.com/plagun98
</a>.
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>

        @section scripts
    {
            <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
            <script src="~/Scripts/underscore.min.js"></script>
            <script src="~/Scripts/app/home.js"></script>
        }
    </div>