NewsBlog/Controllers/ArticlesController.cs
using LibraryAngular.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NewsBlog.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NewsBlog.Controllers
{
    public class ArticlesController : Controller
    {
        private ApplicationDbContext db;

        public ArticlesController()
        {
           db = new ApplicationDbContext();
        }

        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewBag.User = User.Identity.Name;

            var articles = db.Articles.ToList().OrderByDescending(p => p.ID).ToPagedList(pageNumber, pageSize);
            return View("Index", articles);
        }


        public async Task<JsonResult> GetUserInfoByArticle(int id)
        {
            var user = (from a in db.Articles
                        join u in db.Users on a.UserID equals u.Id
                        select new
                        {
                            a.ID,
                            u.FirstName,
                            u.LastName
                        }).Where(x => x.ID == id).ToListAsync();

            var json = Json(await user, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetPublishedArticlesBySearch(string term)
        {
            var articles = (from article in db.Articles
                            join u in db.Users on article.UserID equals u.Id
                            where article.Name.Contains(term) ||
                            article.Description.Contains(term) ||
                            article.Content.Contains(term)
                        orderby article.ID descending
                        select article).Where(x=>x.isAprove==true).ToListAsync();
            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetCategories()
        {
            var categories = (from c in db.Categories select new
            {
                c.ID,
                c.CategoryName
            }).ToListAsync();
            return Json(await categories, JsonRequestBehavior.AllowGet); ;
        }

            public async Task<JsonResult> GetPublishedArticlesByCategory(string category)
        {
            var articles = (from a in db.Articles
                           join u in db.Users on a.UserID equals u.Id
                           where a.isAprove == true
                           orderby a.ViewCount descending
                           where a.Categories.CategoryName == category && a.isAprove==true
                           orderby a.ID 
                           descending
                           select new {
                            a.ID,
                            a.Name,
                            a.isAprove,
                            a.ViewCount,
                            a.CommentsCount,
                            a.DateCreate,
                            a.Description,
                            a.Categories.CategoryName,
                            u.FirstName,
                            u.LastName,
                            u.Id
            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }

        public async Task<JsonResult> GetPublishedAdminChoosedArticles()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isAdminChoose == true && a.isAprove == true
                            orderby a.ID
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }

        public async Task<JsonResult> GetPublishedArticlesByCommentsCount()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isAprove == true
                            orderby a.CommentsCount
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;
        }


        public async Task<JsonResult> GetPopularArticlesByCategory(string category)
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.Categories.CategoryName == category && a.isAprove == true
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).Take(4).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }


        public async Task<JsonResult> GetPublishedHotArticles()
        {
            var articles = (from a in db.Articles
                            join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.ViewCount descending
                            where a.isHotArticle==true && a.isAprove == true
                            orderby a.ID
                            descending
                            select new
                            {
                                a.ID,
                                a.Name,
                                a.isAprove,
                                a.ViewCount,
                                a.CommentsCount,
                                a.DateCreate,
                                a.Description,
                                a.Categories.CategoryName,
                                u.FirstName,
                                u.LastName,
                                u.Id
                            }).ToListAsync();

            var json = Json(await articles, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;
            return json;

        }

      
        public async Task<JsonResult> GetTop3PerWeekArticles()
        {
 
            var now = DateTime.Now;

            int days = now.DayOfWeek - DayOfWeek.Sunday;
            DateTime weekStart = now.AddDays(-days);
            DateTime weekEnd = weekStart.AddDays(7);

            var articles = (from a in db.Articles
                                where a.DateCreate <= weekEnd && a.DateCreate >= weekStart
                                orderby a.ViewCount descending
                                select new { a.ID, a.Name, a.ViewCount, a.CommentsCount, a.isAprove }).Where(x => x.isAprove == true).Take(3).ToListAsync();
                var json = Json(await articles, JsonRequestBehavior.AllowGet);
                json.MaxJsonLength = int.MaxValue;
                return json;

        }

        public async Task<JsonResult> GetPublishedArticles()
        {
            var articles = (from a in db.Articles join u in db.Users on a.UserID equals u.Id
                            where a.isAprove == true
                            orderby a.DateCreate descending

NewsBlog/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewsBlog.Models;

namespace NewsBlog.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        public ActionResult Index()
        {
            var currentUserEmail = System.Web.HttpContext.Current?.User?.Identity?.Name;
            if (currentUserEmail != null)
            {
                var currentUser = db.Users.FirstOrDefault(x => x.Email.Equals(currentUserEmail));
                if (currentUser != null && currentUser.Roles.Any(x => x.RoleId.Equals("1")))
                    return View(db.Categories.ToList());
            }
            return RedirectToAction("NoAccess", "Admin");            
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID, CategoryName")] Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CategoryName")] Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categories);
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            try
            {
                Categories category = db.Categories.Find(id);
                db.Categories.Remove(category);
                db.SaveChanges();
                return Json(new { Success = true });
            }
            catch
            {//TODO: Log error				
                return Json(new { Success = false });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsBlog/Views/Admin/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="~/Content/admin.css" rel="stylesheet" />
</head>
<body>
    <div ng-app="adminApp"  ng-cloak>
        <div ng-controller="adminCtrl as vm">
            <div class="wrapper">
                <div class="row">
                    <div class="col-md-2">
                        <div class="sideMenu">
                            <div class="adminTitle text-center">
                                Admin panel
                            </div>
                            <nav class="sidenav text-center">
                                <ul>
                                    <li><a ng-href="@Url.Action("Index", "Admin")">Новини</a></li>
                                    <li><a ng-href="@Url.Action("Index", "Categories")">Категорії</a></li>
                                    @*<li><a ng-href="@Url.Action("Index", "Manage")">Категорії</a></li>*@
                                </ul>
                            </nav>
                        </div>
                    </div>

                    <div class="col-md-10">
                        <div class="space">
                            <text style="color:gray; font-size:12px;">Всього статей: {{totalItems}}</text>_ <text style="color:gray; font-size:12px;">Відсортовано:{{filteredItems}}</text>
                            <div class="select">
                                <text style="color:gray; font-size:14px;">Сортувати:</text>
                                <select id="select" ng-model="articles" ng-change="update(articles)">
                                    <option value="" ng-if="false"></option>
                                    <option name="all" value="all">Всі</option>
                                    <option value="today">На сьогодні</option>
                                    <option value="weekly">За тиждень</option>
                                    <option value="notallowed">Не затверджені</option>
                                </select>
                            </div>

                            <div class="searchWrap" style="background-color:#fff5b9">
                                <input id="search" type="search" placeholder="Пошук" style="background-color:#fff5b9" ng-model="search">
                            </div>
                            <br />

                            <table class="table">
                                <tr ng-repeat="a in articles | filter:search | Pagestart:(currentPage-1)*PerPageItems | limitTo:PerPageItems track by $id(a.ID)">
                                    @{
                                        var url = Url.Action("GetCoverImage", "Articles", new { id = "{{id=a.ID}}" });
                                        url = HttpUtility.UrlDecode(url);
                                    }
                                    <td>
                                        <img ng-src="@url" width="80" height="80" class="img-thumbnail" />
                                    </td>
                                    <td>
                                        <a ng-href="@Url.Action("news", "Home")?id={{::a.ID}}"> {{::a.Name}} </a>
                                         <div ng-show="{{a.isAprove==true}}" style="color:green; font-size:12px;">Затверджена стаття</div>
                                         <div ng-show="{{a.isAprove==false}}"style="color:red; font-size:12px;">Не затверджена стаття</div>
                                         <div ng-show="{{a.isHotArticle==true}}"style="color:lightgray; font-size:12px;">Гаряча новина</div>
                                         <div ng-show="{{a.isAdminChoose==true}}" style="color:lightgray; font-size:12px;">Вибір редакції</div>
                                    </td>
                                    <td>
                                        <text>
                                            <a ng-href="@Url.Action("setHotArticle","Articles")?id={{a.ID}}">
                                                <span class="glyphicon glyphicon-fire" style="color:orangered"></span>
                                            </a>&emsp;
                                            <a ng-href="@Url.Action("setAdminChoosedArticle","Articles")?id={{a.ID}}">
                                                <span class="glyphicon glyphicon-bell" style="color:#ffd800"></span>
                                            </a>
                                        </text>
                                    </td>
                                    <td>
                                        <a ng-href="@Url.Action("Edit", "Articles")?id={{::a.ID}}"><span class="glyphicon glyphicon-edit"></span></a><br />
                                        <a ng-href="#" class="" ng-confirm-click="Are you sure to delete this record ?" confirmed-click="removeArticle(a.ID)"><span class="glyphicon glyphicon-remove"></span></a><br />
                                        <a ng-href="@Url.Action("isAproved","Admin")?id={{a.ID}}">
                                            <span class="glyphicon glyphicon-ok" style="color:forestgreen"></span>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            
                            <div class="castPager">
                                <button type="button" class="btn btn-success btn-sm" ng-disabled="currentPage == 1"
                                        ng-click="currentPage=currentPage-1">
                                    Назад
                                </button>
                                <span>Стр. {{currentPage}} з {{ numberOfPages() }}</span>

                                <button type="button" class="btn btn-success btn-sm" ng-disabled="currentPage == numberOfPages()"
                                        ng-click="currentPage = currentPage+1">
                                    Далі
                                </button>
                            </div>


                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>
</html>

@section scripts{
    <script src="~/Scripts/app/admin.js"></script>
}

NewsBlog/Views/Admin/NoAccess.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>У вас нету доступа на эту страничку.</title>
</head>
<body>
    <div>
        <p>У вас нету доступа на эту страничку.</p>
    </div>
</body>
</html>